name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude '^https://codecov\.io/gh/earth-metabolome-initiative/geometric-traits(/.*)?$'
            --exclude '^https://doi\.org/10\.3115/981732\.981751/?$'
            './**/*.md'
            './**/*.html'
          fail: true
